LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := Selfie
LOCAL_MODULE_CLASS := APPS
LOCAL_PRODUCT_MODULE := true
LOCAL_CERTIFICATE := $(DEFAULT_SYSTEM_DEV_CERTIFICATE)

LOCAL_OVERRIDES_PACKAGES := Camera2

LOCAL_MODULE_TARGET_ARCH := arm64
LOCAL_SRC_FILES := prebuilt/selfie.apk

include $(BUILD_PREBUILT)
